# Generated by Django 6.0.4 on 2026-04-23 21:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('survey', 'Complete a Survey'), ('quiz', 'Complete a Quiz'), ('game', 'Play a Game'), ('streak', 'Maintain Streak'), ('referral', 'Refer a Friend'), ('ad', 'Watch Ads')], max_length=20)),
                ('target', models.IntegerField(default=1)),
                ('points_reward', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='source',
            field=models.CharField(choices=[('survey', 'Survey'), ('quiz', 'Quiz'), ('game', 'Game'), ('ad_watch', 'Ad Watch'), ('referral', 'Referral'), ('daily_login', 'Daily Login'), ('streak_bonus', 'Streak Bonus'), ('task', 'Task'), ('redemption', 'Redemption'), ('admin', 'Admin'), ('signup_bonus', 'Signup Bonus'), ('spin_wheel', 'Spin Wheel'), ('daily_challenge', 'Daily Challenge')], max_length=20),
        ),
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_won', models.IntegerField(default=0)),
                ('label', models.CharField(max_length=50)),
                ('spun_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-spun_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.dailychallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
